### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by 1995parham** [AUT-CEIT/AUTPortal#1]
How can we use OCR methods in order to parse portal captcha? 🤔 
@Tabrizian @pi0 @rajabiseraji @sajjadrahnama7 @aliir74

**Comment by pi0** [comment]
@1995parham I've tried this once before. Best results were using google `tesseract-ocr` (With a python wrapper) and custom font set extracted from portal samples. Anyway, don't think we can easily bypass captcha in main page (Maybe two letter ones are easier). Consider that same captcha algorithm is being used for [Mellat](https://ebanking.bankmellat.ir/ebanking/) !

Something else to note: There is a tight rate-limit per requests to prevent scripts working.
